name: ScanCode Toolkit Scan

on:
  workflow_dispatch:
    inputs:
      scan_type:
        description: "Scan type: repo | zip | docker"
        required: true
        default: "repo"
      repo_url:
        description: "Repo URL (if scan_type=repo)"
        default: "https://github.com/example/repo.git"
      archive_file:
        description: "Archive file (if scan_type=zip)"
        default: "sample.zip"
      docker_image:
        description: "Docker image (if scan_type=docker)"
        default: "alpine:latest"

      enable_license_scan:
        type: boolean
        description: "Run license + license-text detection"
        default: true
      enable_copyright_scan:
        type: boolean
        description: "Run copyright + author + email detection"
        default: true
      enable_metadata_scan:
        type: boolean
        description: "Run metadata scans (urls + file info)"
        default: false
      enable_package:
        type: boolean
        description: "Detect packages and manifests"
        default: true
      enable_sbom_export:
        type: boolean
        description: "Export SPDX and CycloneDX SBOM"
        default: false

jobs:
  scancode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y git unzip jq python3 python3-pip && \
          pip3 install pandas openpyxl

      - name: Prepare input
        run: |
          set -euo pipefail
          SCAN_TYPE="${{ github.event.inputs.scan_type }}"
          REPO_URL="${{ github.event.inputs.repo_url }}"
          ARCHIVE_FILE="${{ github.event.inputs.archive_file }}"
          DOCKER_IMAGE="${{ github.event.inputs.docker_image }}"

          case "$SCAN_TYPE" in
            repo)
              git clone "$REPO_URL" input_repo
              INPUT_PATH="input_repo"
              LABEL="$(basename "${REPO_URL%.*}")"
              ;;
            zip)
              unzip -q "$ARCHIVE_FILE" -d input_zip
              INPUT_PATH="input_zip"
              base="$(basename "$ARCHIVE_FILE")"; LABEL="${base%.*}"
              ;;
            docker)
              docker pull "$DOCKER_IMAGE"
              docker save "$DOCKER_IMAGE" -o docker-image.tar
              INPUT_PATH="docker-image.tar"
              LABEL="$(echo "$DOCKER_IMAGE" | tr '/:' '__')"
              ;;
            *)
              echo "❌ Unknown scan_type: $SCAN_TYPE"
              exit 1
              ;;
          esac

          echo "INPUT_PATH=$INPUT_PATH" >> $GITHUB_ENV
          echo "SCAN_LABEL=$LABEL" >> $GITHUB_ENV

      - name: Download ScanCode Toolkit
        run: |
          git clone --depth 1 https://github.com/nexB/scancode-toolkit.git
          cd scancode-toolkit
          ./scancode --version

      - name: Run ScanCode Toolkit
        run: |
          cd scancode-toolkit
          SCANCODE_OPTS=""

          if [ "${{ github.event.inputs.enable_license_scan }}" = "true" ]; then
            SCANCODE_OPTS="$SCANCODE_OPTS --license --license-text"
          fi
          if [ "${{ github.event.inputs.enable_copyright_scan }}" = "true" ]; then
            SCANCODE_OPTS="$SCANCODE_OPTS --copyright --email"
          fi
          if [ "${{ github.event.inputs.enable_metadata_scan }}" = "true" ]; then
            SCANCODE_OPTS="$SCANCODE_OPTS --url --info"
          fi
          if [ "${{ github.event.inputs.enable_package }}" = "true" ]; then
            SCANCODE_OPTS="$SCANCODE_OPTS --package"
          fi

          OUT_PREFIX="$GITHUB_WORKSPACE/scancode_${SCAN_LABEL}"
          IN_PATH="$GITHUB_WORKSPACE/$INPUT_PATH"

          ./scancode $SCANCODE_OPTS --json-pp "${OUT_PREFIX}.json" "$IN_PATH"

          if [ "${{ github.event.inputs.enable_sbom_export }}" = "true" ]; then
            ./scancode --spdx-tv   "${OUT_PREFIX}.spdx.tv"   "$IN_PATH"
            ./scancode --spdx-rdf  "${OUT_PREFIX}.spdx.rdf"  "$IN_PATH"
            ./scancode --cyclonedx-json "${OUT_PREFIX}.cdx.json" "$IN_PATH"
          fi

          echo "OUT_PREFIX=$OUT_PREFIX" >> $GITHUB_ENV

      - name: Convert JSON → CSV + Excel
        run: |
          python3 - <<'EOF'
          import pandas as pd, json, glob, os

          licenses_rows, files_rows, packages_rows = [], [], []

          # Look for all ScanCode JSON outputs
          for json_file in glob.glob("scancode_*.json"):
              with open(json_file, "r", encoding="utf-8") as f:
                  try:
                      data = json.load(f)
                  except Exception:
                      continue

              # Case 1: license findings (list of licenses with reference_matches)
              if isinstance(data, list) and data and "license_expression" in data[0]:
                  for lic in data:
                      for ref in lic.get("reference_matches", []):
                          licenses_rows.append({
                              "file_path": ref.get("from_file"),
                              "license_expression": lic.get("license_expression"),
                              "license_expression_spdx": lic.get("license_expression_spdx"),
                              "matched_text": ref.get("matched_text"),
                              "start_line": ref.get("start_line"),
                              "end_line": ref.get("end_line"),
                              "rule_url": ref.get("rule_url"),
                          })

              # Case 2: file-by-file scan results
              elif isinstance(data, dict) and "files" in data:
                  for fi in data["files"]:
                      files_rows.append({
                          "path": fi.get("path"),
                          "type": fi.get("type"),
                          "licenses": "; ".join([
                              str(lic.get("spdx_license_key",""))
                              for lic in fi.get("licenses", [])
                              if lic.get("spdx_license_key")
                          ]),
                          "copyrights": "; ".join([
                              str(c.get("value",""))
                              for c in fi.get("copyrights", [])
                              if c.get("value")
                          ]),
                          "emails": "; ".join([
                              str(e.get("value",""))
                              for e in fi.get("emails", [])
                              if e.get("value")
                          ]),
                          "urls": "; ".join([
                              str(u.get("value",""))
                              for u in fi.get("urls", [])
                              if u.get("value")
                          ]),
                      })

                      for p in fi.get("packages", []):
                          packages_rows.append({
                              "package_url": p.get("package_url"),
                              "type": p.get("type"),
                              "name": p.get("name"),
                              "version": p.get("version"),
                              "license_expression": p.get("license_expression"),
                          })

          # Convert to DataFrames
          df_lic = pd.DataFrame(licenses_rows) if licenses_rows else pd.DataFrame()
          df_files = pd.DataFrame(files_rows) if files_rows else pd.DataFrame()
          df_pkg = pd.DataFrame(packages_rows) if packages_rows else pd.DataFrame()

          # --- Summaries for management view ---
          summary_blocks = []

          if not df_lic.empty:
              license_summary = df_lic.groupby("license_expression_spdx")["file_path"].count().reset_index()
              license_summary.rename(columns={"file_path": "file_count"}, inplace=True)
              license_summary.insert(0, "Category", "License Summary")
              summary_blocks.append(license_summary)

          if not df_files.empty:
              copyright_summary = df_files[["path", "copyrights"]].copy()
              copyright_summary.insert(0, "Category", "Copyrights")
              summary_blocks.append(copyright_summary)

          if not df_pkg.empty:
              pkg_summary = df_pkg[["type", "name", "version", "license_expression"]].copy()
              pkg_summary.insert(0, "Category", "Packages")
              summary_blocks.append(pkg_summary)

          df_summary = pd.concat(summary_blocks, ignore_index=True) if summary_blocks else pd.DataFrame()

          # Output Excel named after repo/archive
          scan_label = os.getenv("SCAN_LABEL", "scancode")
          out_xlsx = f"scancode_{scan_label}.xlsx"

          with pd.ExcelWriter(out_xlsx) as w:
              if not df_files.empty: df_files.to_excel(w, "Files_Detail", index=False)
              if not df_lic.empty: df_lic.to_excel(w, "Licenses_Detail", index=False)
              if not df_pkg.empty: df_pkg.to_excel(w, "Packages", index=False)
              if not df_summary.empty: df_summary.to_excel(w, "Summary", index=False)

              # 🔑 Ensure at least one sheet exists
              if all(df.empty for df in [df_files, df_lic, df_pkg, df_summary]):
                  pd.DataFrame([{"info": "No data extracted"}]).to_excel(
                      w, sheet_name="Empty", index=False
                  )

          print(f"✅ Wrote Excel: {out_xlsx}")
          EOF

      - name: Upload ScanCode reports
        uses: actions/upload-artifact@v4
        with:
          name: scancode-reports-${{ env.SCAN_LABEL }}
          path: |
            scancode_${{ env.SCAN_LABEL }}.json
            scancode_${{ env.SCAN_LABEL }}.xlsx
            scancode_${{ env.SCAN_LABEL }}.spdx.tv
            scancode_${{ env.SCAN_LABEL }}.spdx.rdf
            scancode_${{ env.SCAN_LABEL }}.cdx.json
