name: "ScanCode Toolkit Scan (Repo / Folder / Zip / Tar / Docker)"

on:
  workflow_dispatch:
    inputs:
      scan_type:
        description: "What to scan"
        required: true
        type: choice
        options: [repo, folder, zip, tar, docker]
        default: repo

      # --- REPO / FOLDER ---
      repo_url:
        description: "Repo URL (for scan_type=repo or folder)"
        required: false
        default: "https://github.com/psf/requests.git"
      git_ref:
        description: "Branch / tag / commit (optional; if blank and URL has /tree/<ref> or /releases/tag/<tag>, that wins)"
        required: false
        default: ""
      folder_path:
        description: "Subfolder inside the repo to scan (only if scan_type=folder)"
        required: false
        default: ""

      # --- ARCHIVES ---
      archive_url:
        description: "Download URL for .zip/.tar/.tar.gz (for scan_type=zip/tar)"
        required: false
        default: ""
      archive_file:
        description: "Archive file in the repo workspace (for scan_type=zip) e.g., sample.zip"
        required: false
        default: "sample.zip"

      # --- DOCKER ---
      docker_image:
        description: "Docker image (for scan_type=docker)"
        required: false
        default: "alpine:latest"

      # --- SCANCODE TOGGLES ---
      enable_license_scan:
        type: boolean
        description: "Run license + license-text detection"
        default: true
      enable_copyright_scan:
        type: boolean
        description: "Run copyright + author + email detection"
        default: true
      enable_metadata_scan:
        type: boolean
        description: "Run metadata scans (urls + file info)"
        default: false
      enable_package:
        type: boolean
        description: "Detect packages and manifests"
        default: true
      enable_sbom_export:
        type: boolean
        description: "Export SPDX and CycloneDX SBOM"
        default: false
