name: ScanCode Toolkit Scan (Repo / Folder / Zip / Tar / Docker)

on:
  workflow_dispatch:
    inputs:
      scan_type:
        description: "Scan type"
        required: true
        type: choice
        options:
          - repo
          - zip
          - docker
        default: repo

      docker_image:
        description: "Docker image (if scan_type=docker)"
        required: false
        default: "alpine:latest"

      repo_url:
        description: "Repo URL (if scan_type=repo)"
        required: false
        default: "https://github.com/psf/requests.git"

      git_ref:
        description: "Branch / tag / commit to scan (leave blank if included in repo_url via /tree/<ref> or /releases/tag/<tag>)"
        required: false
        default: ""

      archive_file:
        description: "Archive file (if scan_type=zip)"
        required: false
        default: "sample.zip"

      enable_license_scan:
        type: boolean
        description: "Run license + license-text detection"
        default: true
      enable_copyright_scan:
        type: boolean
        description: "Run copyright + author + email detection"
        default: true
      enable_metadata_scan:
        type: boolean
        description: "Run metadata scans (urls + file info)"
        default: false
      enable_package:
        type: boolean
        description: "Detect packages and manifests"
        default: true
      enable_sbom_export:
        type: boolean
        description: "Export SPDX and CycloneDX SBOM"
        default: false
