name: ScanCode Toolkit Scan

on:
  workflow_dispatch:
    inputs:
      scan_type:
        description: "Scan type"
        required: true
        type: choice
        options:
          - repo
          - zip
          - docker
        default: repo
